[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pipen-cli-init"
version = "1.1.1"
description = "A pipen cli plugin to create a pipen project (pipeline)"
authors = [
    {name = "pwwang", email = "pwwang@pwwang.com"},
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pipen>=1.1",
    "copier>=9",
]

[project.entry-points."pipen_cli"]
cli-init = "pipen_cli_init:PipenCliInit"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
